#This is a simple dockerfile for running a dev env for C coding

FROM debian

RUN apt-get update -y  && apt-get upgrade -y
RUN apt-get build-essential -y && apt-get install vim -y && apt-get install git -y
